### ISSUE TITLE
Question please

### ISSUE THREAD

**Issue by agony09** [ozh/cookieclicker#19]
Hello, I have a question about this script.
Is it free? Can I just use it? (If I translated it from English to any other national language)
Or do I have to pay attention to something?
I do not intend to use it commercially in any way.
I look forward to your response. 
Best regards, thank you.

P.S .: Does a certain PHP version have to be available for this?

**Comment by ozh** [comment]
It's all in the readme dude. Head to http://orteil.dashnet.org/cookieclicker/ and click on "Info"

**Comment by agony09** [comment]
ahhh okay, thanks a lot for this hint.
"is free - forever", ok thanks.
is this the newest version ?
(i ask bevore i start translate the script)

**Comment by agony09** [comment]
I'm sorry, I can't find it in the "info" exactly. Is the game free or is the script free?
I want to prevent misunderstandings.
