### ISSUE TITLE
Update to The latest version (2.021)

### ISSUE THREAD

**Issue by Ian-Luedke** [ozh/cookieclicker#3]
The current game is out of date and is not compatible with current saves and imports and exports, If you are not willing to update the game, could you let me know how you got the code so I can do it, also if you decide not to update it could you tell me why. Thanks a ton! 
-il21416@dce.k12.wi.us
-luedke.ian@gmail.com

**Comment by ozh** [comment]
I think it's updated, please test & report if you think anything has been forgotten
