### ISSUE TITLE
oops. wrong address error

### ISSUE THREAD

**Issue by DaMonkeExe** [ozh/cookieclicker#45]
shows this once i load it, anyway to fix ?
![image](https://user-images.githubusercontent.com/97502204/157637056-995d03d4-1d44-47cd-a989-15471c8ba693.png)

**Comment by AnonOne666** [comment]
I would try to redownload because I didn't have that problem when I downloaded today.

**Comment by DaMonkeExe** [comment]
im hosting it at my site so maybe thats the problem

**Comment by ozh** [comment]
seems that http://ozh.github.io/cookieclicker/ works fine
