### ISSUE TITLE
grab.php

### ISSUE THREAD

**Issue by capozzme** [ozh/cookieclicker#46]
Hi, 
It looks like the call to grab.php is failing.  This is causing the heralds to be set to 0. 

Line 1883 			ajax('/patreon/grab.php',Game.GrabDataResponse);

Looks like the file is used at 
http://orteil.dashnet.org/patreon/grab.php?nocache=1647903804809

I think if you had a new repository with ozah/patreon and put the grab.php there it could work.

**Comment by capozzme** [comment]
{"herald":41,"grandma":"﻿Patreona|Janice|Gabrielle|Grandma McGrandmaface|Charlie|\"egg\" Sr.|Jet-dayo|Natsuki|Ivy|Rose|Babayaga|Grandma #42|SneakySquid|Swad Plan|Meep Moop|Psychedelic Rapper Andrew JD|Telos|Moondoge|Lily Bowen|Mrs PoopyButthole|Mrs Sugai Kirin|Survivor of the Stale|Betty Ann Niemi|Tjien Nio|The First Baker|Mamichette|dQw4w9WgXcQ|Carmelina Calabrese|The GrandNut|La mere Michel|Aune Mummo|Jeff Junior|Her?|Rydh|Euphegenia Doubtfire|Bear|How did you find me, JUNESUK?|Ahtelo|Steve...?|Fanny|DAF Pvnk - Mother of trucks|Koisuru Fortune Grandma|Lieselotte|Izual Rebirth|Cosma-Tanti|Starco|Knitting Slave|Forgotten Abbey|Granny Rags|Mrs. Fizzwidget|Nakamoto|Zan Tart-izanne|The Roach Queen|Khookiesi, Grandmother of Dragonflights|Hey guys, Dexterfan99 here|Aryll|Ms. Chievous|Don't Stop Me Now|Dauna|Gerry|Erina Pendleton-Joestar|Stacy's Grandma|Benyboy|Rosie Beestinger|Tesco employee #65|Oda|Grandma Jones|Dan|Krieg|Chris|Kamilla|Tandy|Elisabeth|MinionMemer|Eanydo Erdman|Cookieatron4000|TechhX|Turtlenator|Carmelina|Shiny Blue Grandma|Anne|Penka|\"Hey guys, it's Nicole\"|Cora|Freya28|Kiwibajs|EEEEEE|Ms. Denis Gur Arie|Idling Vasha|?????|Tammie|Grandma Kara|Sanda Reiss|Alex|Mirle|Audrey|Ittle Dew|You're Killing Me Smols|Baker? I hardly know her!|A Duplicate Grandma|Betty Margaret Davis|Chlorophyte Grandma|Felpinhazinha|Satan's grandmother|Ruby Rose|Miyori Grandma|Geuser|Anneliese|Pielak|Swamper|Pikachi|Grackitz|Deborah Wright|BUT IT WAS ME, DIO!|Barbara|SERAS FAMO!!!|Audrey Porter|Benny Zhy|Doctergreen|Kage|Jarvis Fishwick|Elder Pledge 666x in a row...|Tell Cersei, it was me.|Kimahri|Henrietta Gertrude|Tyler Liddick|noisypineapples|Linda-Bea Dolvoy|DevilishWarrior|Exterminator|Matthue Loose|Caden|moist butterscotch lips|Alireah|Fey Yoshida|Aviators|Ashlee <3|He Had Boxing Gloves On|Falling Collin|Error 404: Name not Found|Groz|Granny Jonathan|Hanna Highmark|Nonmoving Osmond|The Worm Which Waits|Lurking Tealeaf|Ruby Wrinkle|Her|\"Eggy Grandma\"|Cookie maker 100|Addison Bennett|Nasus|Only 30 characters, huh? Fine.|Matt Was Here|ScartTheWaz|Tanyac Crimson|Ume Ito|VenMissa|Velma Francis|amdnarG|Leota Marie|Nikola|Grandmommy Celestine|Annuziatta|hosh...|E|Joe Grandmomma|Granny Grearest|Vivian|Vovó Dal|Baker of Steak Cookies|Aku daikan|SkeletonJoke|David loves Rachel! <3|Polar|Loremaster Rawlins|lickin my cookie|Fmaily Gyu funy momens #420|Ms. Cppkies|WillStreet|Ian's Mom|Grandma Divah|Betty BeardPuller|Mamie Cobol|200rassberris|ipm1234|Galadion|Olive Gardenia|Megan I. McIntosh|Lady Sweets|Rivne|Autosuffisant|BoShek|Brooke Chumbers|Cthulhu|ɐɯpuɐɹפ|binbinuser|Amma Jóna|the book was empty|Berit|DRIFTER1117|Yackemflam|Help me|YeOl'GrammityGram|Mason W|Peggy Hattenfels|majik|latte|amogus|Samuel Robertson|Anneliese Albina Emma|Barack Obama|Gramma Margaret"}

contents of grab.php

**Comment by ozh** [comment]
I imagine the returned content of this call varies at some point ? If so, there's nothing that can be done to really mirror it

**Comment by capozzme** [comment]
Looks like heralds is always harcoded to 41

https://cookieclicker.fandom.com/wiki/Heralds

Trivia
The herald count is currently hard-coded to be at 41 in the browser version: [/patreon/grab.php](http://orteil.dashnet.org/patreon/grab.php). It is therefore incongruent with the number of patrons with the herald tier at the Dashnet Patreon page.
However, in the Steam version of the game, the maximum number of heralds is increased to 100. As stated above, the amount of heralds is calculated by dividing the number of players currently playing the game by 100. It is currently unknown as to the reason for this difference,

**Comment by ozh** [comment]
So, it seems that the solution to this is : 

- modify that line 1883  to return a hard coded value such as the one you describe
- update the "[How to update](https://github.com/ozh/cookieclicker#how-to-update)" section of the README to explain that change and that future updates should check if [http://orteil.dashnet.org/patreon/grab.php](http://orteil.dashnet.org/patreon/grab.php?nocache=1647903804809) has changed its return

Pull Request anyone?

**Comment by Lugixion** [comment]
Hey! I checked this problem and downloading the grab.php file would be enough and that would make it easier if it gets uptaded, can I just pull request it or it has to be hard coded?

**Comment by ozh** [comment]
Pull request welcome !
