### ISSUE TITLE
"Oops! Wrong domain!"

### ISSUE THREAD

**Issue by ProbablyKam** [ozh/cookieclicker#48]
I got this message when I embedded a github pages from a forked repository to a google site. Anybody got a fix?

**Comment by ozh** [comment]
There's no such thing as "embed a github page to a google site"... (or I don't understand what you describe)

You're supposed to clone and host this yourself somewhere

**Comment by ghost** [comment]
Im embedding the github pages website (because in google sites you can embed a whole website) and when i do that it says "oops wrong domain" i was wondering if you could tell me where the code that does that is so i can remove it in my fork.

**Comment by ghost** [comment]
Why did you close this the issue hasn't been solved?

**Comment by ozh** [comment]
This repo is a mirror of the original site, it's not my code. I'm closing because this is not an issue with my mirror. It's not even an issue with the original site : if you're trying to "embed" it and the original site doesn't work, it is by design.

**Comment by ghost** [comment]
Oh i just wanted to know if you knew the peice of code that does this, but since im getting the impression you just ripped all the code from the original site then I don't believe you have the answer so closing this is fine.

**Comment by ghost** [comment]
Have a nice day.

**Comment by ozh** [comment]
> im getting the impression you just ripped all the code from the original site

Dude 🤣 It's literally explained on the repo page that this is a **mirror** of the original site and I even provided instructions on how to completely **copy the code** of the original site :)
