### ISSUE TITLE
How to remove "Oops Wrong Address" dialog?

### ISSUE THREAD

**Issue by TG20YT** [ozh/cookieclicker#53]
Hello! I was wondering how I would be able to bypass the dialog that appears when hosting cookie clicker on a website other than it's official one. I'm trying to host it on Glitch for an unblocked games site, but this damn popup doesn't go away. Can someone help me out please? The web address I'm hosting it on is https://cookieclicker-ubh.glitch.me
![com oculus shellenv-20221213-161401](https://user-images.githubusercontent.com/79722408/207457391-f8d69ada-1a34-4381-a31e-8a7c57ab7ebb.jpg)

Yes, I'm doing it in VR. I typed this in VR

**Comment by kurbus** [comment]
writing code in vr is absolutely insane 
Why though

**Comment by crustysoup** [comment]
how did you end up fixing this?

**Comment by kurbus** [comment]
> how did you end up fixing this?

#48

**Comment by xzcollapse** [comment]
@TG20YT if you go into the main.js file and scroll all the way down and start going up slowly, you can look for the if statement if(top!=self) and remove it. dont remove the code in it, just the if, the else, the Game.ErrorFrame(), and the brackets
  
your welcome

**Comment by xzcollapse** [comment]
for more information, that error occurs when the website is in an iframe, so it can't get copied the glitch webview is an iframe of the website. if you were to go to the website itself in a new tab, it would work completely.. it was mirrored though, so that code is now useless, but they keep it for some reason. **if you dont know how to do the fix, send the main.js file in this issue and i can remove it.**

**Comment by ozh** [comment]
There is no "oops wrong address" : http://ozh.github.io/cookieclicker/

**Comment by Fluffernater** [comment]
The line is 16865, if anyone is here.

**Comment by Lia-Games** [comment]
> @TG20YT if you go into the main.js file and scroll all the way down and start going up slowly, you can look for the if statement if(top!=self) and remove it. dont remove the code in it, just the if, the else, the Game.ErrorFrame(), and the brackets
> 
> your welcome

For some reason it just infinitely loads when i do this

**Comment by Fluffernater** [comment]
> > @TG20YT if you go into the main.js file and scroll all the way down and start going up slowly, you can look for the if statement if(top!=self) and remove it. dont remove the code in it, just the if, the else, the Game.ErrorFrame(), and the brackets
> > your welcome
> 
> For some reason it just infinitely loads when i do this

did you do it on line 16865? theres another one near it that makes it infinitely load

**Comment by Fri3s** [comment]
@Fluffernater i couldn't find the other one, could you possibly specify the line?
Thanks

**Comment by Fri3s** [comment]
> > > @TG20YT if you go into the main.js file and scroll all the way down and start going up slowly, you can look for the if statement if(top!=self) and remove it. dont remove the code in it, just the if, the else, the Game.ErrorFrame(), and the brackets
> > > your welcome
> > 
> > 
> > For some reason it just infinitely loads when i do this
> 
> did you do it on line 16865? theres another one near it that makes it infinitely load

I couldn't find the other one, could you possibly specify the line?

**Comment by Elephantkid** [comment]
> > > > @TG20YT if you go into the main.js file and scroll all the way down and start going up slowly, you can look for the if statement if(top!=self) and remove it. dont remove the code in it, just the if, the else, the Game.ErrorFrame(), and the brackets
> > > > your welcome
> > > 
> > > 
> > > For some reason it just infinitely loads when i do this
> > 
> > 
> > did you do it on line 16865? theres another one near it that makes it infinitely load
> 
> I couldn't find the other one, could you possibly specify the line?

Remove line 16865, 16866, 16867, 16878.  I think you also need to unindent the code which would have been in the brackets but not too sure about that.

**Comment by ImmediateMurderProfessionals** [comment]
> > > > > @TG20YT if you go into the main.js file and scroll all the way down and start going up slowly, you can look for the if statement if(top!=self) and remove it. dont remove the code in it, just the if, the else, the Game.ErrorFrame(), and the brackets
> > > > > your welcome
> > > > 
> > > > 
> > > > For some reason it just infinitely loads when i do this
> > > 
> > > 
> > > did you do it on line 16865? theres another one near it that makes it infinitely load
> > 
> > 
> > I couldn't find the other one, could you possibly specify the line?
> 
> Remove line 16865, 16866, 16867, 16878. I think you also need to unindent the code which would have been in the brackets but not too sure about that.

Is 16878 the one that says, "if (App && App.loadMods) App.loadMods(launch);"?

**Comment by xzcollapse** [comment]
Due to the game being extremely updated since I said this, line 16878 and
others are absolutely not correct anymore. If you search (ctrl-f) for “top
!== self” and replace that with “true” obviously without quotes on either
of them. Happy playing :)
