### ISSUE TITLE
Make an updater program

### ISSUE THREAD

**Issue by kailando** [ozh/cookieclicker#78]
Please make an **updater** program that gets ran when the game runs.
It'll make it better for users.

**Comment by plasma4** [comment]
Updater programs tend to be quite complicated (at least from a webpage standpoint); from my experience with it, you have to do a mangled mess of XMLHttpRequests and whatnot. Loading like 50MB of temporary storage isn't really an optimal solution for a game that gets updated maybe once or twice a year.

**Comment by om3ga6400** [comment]
> Please make an **updater** program that gets ran when the game runs. It'll make it better for users.

there already one but you just have to run it separately

**Comment by ozh** [comment]
Update instructions are in the readme. Making an updater would just lead to more issues

**Comment by kailando** [comment]
Come on, it would be nice for it to just be, like, a Python program or smth
for updating instead of whatever

**Comment by plasma4** [comment]
You can use shell to do that, use the .sh file from [over here](https://github.com/ozh/cookieclicker/blob/gh-pages/update.sh).
